version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: DockerFile
    container_name: frontend_app
    ports:
      - "3000:80"
    networks:
      - app_network

networks:
  app_network:
    external: true